name: therapytrain
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - anaconda
  - pip
  - pyppeteer
  - pip:
    - -r requirements.txt
    - -r tools/requirements.txt
    - python-dotenv