name: Create Environments

on:
  workflow_dispatch:

jobs:
  create-environments:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      actions: write
    
    steps:
      - name: Create staging environment
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/staging \
            -d '{"wait_timer":0,"reviewers":["vivirox"]}'
      
      - name: Create production environment
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/production \
            -d '{"wait_timer":30,"reviewers":["vivirox"]}' 