name: Create Environments

on:
  workflow_dispatch:

jobs:
  create-environments:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      actions: write
    
    steps:
      - name: Create staging environment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method PUT /repos/${{ github.repository }}/environments/staging \
            -H "Accept: application/vnd.github+json" \
            -f wait_timer=0 \
            -f reviewers='["vivirox"]'
      
      - name: Create production environment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method PUT /repos/${{ github.repository }}/environments/production \
            -H "Accept: application/vnd.github+json" \
            -f wait_timer=30 \
            -f reviewers='["vivirox"]' 