name: Create Environments

on:
  workflow_dispatch:

jobs:
  create-environments:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      actions: write
    
    steps:
      - name: Authenticate with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GITHUB_TOKEN"

      - name: Create staging environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method PUT /repos/${{ github.repository }}/environments/staging \
            -f wait_timer=0 \
            -f reviewers='["vivirox"]'
      
      - name: Create production environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method PUT /repos/${{ github.repository }}/environments/production \
            -f wait_timer=30 \
            -f reviewers='["vivirox"]' 