name: Create Environments

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  actions: read

jobs:
  create-environments:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Preview environment
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/Preview \
            -d '{"wait_timer":0,"reviewers":["vivirox"]}'
      
      - name: Create Production environment
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/Production \
            -d '{"wait_timer":30,"reviewers":["vivirox"]}'