name: Initialize Environments

on:
  workflow_dispatch:

jobs:
  init-preview:
    name: Initialize Preview
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: https://preview.therapytrain.com

    steps:
      - name: No-op step
        run: echo "Initializing preview environment"

  init-production:
    name: Initialize Production
    runs-on: ubuntu-latest
    environment:
      name: live
      url: https://therapytrain.com

    steps:
      - name: No-op step
        run: echo "Initializing production environment" 