name: Unit Tests

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: therapytrain
        environment-file: environment.yml
        python-version: "3.10"
        auto-activate-base: false
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda info
        conda list
        pnpm install puppeteer
        
    - name: Copy environment file
      shell: bash -l {0}
      run: |
        cp .env.example .env
        
    - name: Run tests
      shell: bash -l {0}
      env:
        ANTHROPIC_API_KEY: ${{ secrets['ANTHROPIC_API_KEY'] }}
        OPENAI_API_KEY: ${{ secrets['OPENAI_API_KEY'] }}
        GOOGLE_API_KEY: ${{ secrets['GOOGLE_API_KEY'] }}
      run: |
        PYTHONPATH=. python -m unittest discover tests/
