name: Unit Tests

permissions:
  contents: read

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10.16
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.16
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Copy environment file
        run: |
          cp .env.example .env

      - name: Run tests
        env:
          ANTHROPIC_API_KEY: ${{ secrets['ANTHROPIC_API_KEY'] }}
          OPENAI_API_KEY: ${{ secrets['OPENAI_API_KEY'] }}
          GOOGLE_API_KEY: ${{ secrets['GOOGLE_API_KEY'] }}
        run: |
          PYTHONPATH=. python -m unittest discover tests/
